module.exports=function(app,controllers){
		app.get('/',controllers.index.home);
		app.post('/signup',controllers.account.signup);
		app.post('/ajax/checkEmail',controllers.ajax.checkEmail);
    	app.post('/ajax/checkEmailAddProject',controllers.ajax.checkEmailAddProject);
    	app.post('/ajax/checkProjectCode',controllers.ajax.checkProjectCode);
    	app.post('/ajax/getName',controllers.ajax.getName);
		app.post('/login',controllers.account.login);
		app.get('/logout',controllers.account.logout);
		app.get('/add-project',controllers.todo.add_project);
		app.post('/save-project',controllers.todo.save_project);
		app.get('/edit-project',controllers.todo.edit_project);
		app.get('/delete-project/:id',controllers.todo.delete_project);
   		app.get('/add-task',controllers.todo.add_task);
		app.post('/save-task',controllers.todo.save_task);
		app.get('/edit-task',controllers.todo.edit_task);
		app.get('/delete-task/:id&:project',controllers.todo.delete_task);
		app.get('/export-excel',controllers.other.export_excel);
		app.get('/show-task',controllers.todo.show_task);
	}
