module.exports=function(app,controllers){
		app.get('/',controllers.index.home);
		app.post('/signup',controllers.account.signup);
		app.post('/ajax/checkEmail',controllers.ajax.checkEmail);
    	app.post('/ajax/checkEmailAddProject',controllers.ajax.checkEmailAddProject);
    	app.post('/ajax/checkProjectCode',controllers.ajax.checkProjectCode);
		app.post('/login',controllers.account.login);
		app.get('/logout',controllers.account.logout);
		app.get('/add-project',controllers.todo.add_project);
		app.post('/save-project',controllers.todo.save_project);
		app.get('/edit-project/:id',controllers.todo.edit_project);
		app.get('/delete-project/:id',controllers.todo.delete_project);
		app.post('/save-todo',controllers.todo.save_todo);
		app.get('/edit-todo/:id',controllers.todo.edit_todo);
		app.get('/delete-todo/:id',controllers.todo.delete_todo);
		app.get('/export-excel',controllers.other.export_excel);
	}
